server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # учебный API под тем же адресом, что и сайт (как на lang.deev.su)
    location /api/ {
        resolver 1.1.1.1 8.8.8.8 valid=300s;
        set $api exam-api-courses.std-900.ist.mospolytech.ru;
        proxy_pass http://$api$request_uri;
        proxy_set_header Host $api;
    }
}
